-- ============================================================
-- NICBEAUTTY - SCHEMA COMPLETO (banco novo)
-- Rodar no SQL Editor do projeto jfqfbpjimozevtjscbej
-- ============================================================

-- ---------- TABELAS ----------

create table if not exists public.services (
  id integer primary key generated by default as identity,
  nome text not null,
  descricao text,
  duracao text,
  aplicacao text,
  manutencao jsonb default '[]'::jsonb,
  imagem text,
  textobotao text,
  created_at timestamptz null default now()
);

create table if not exists public.feedbacks (
  id integer primary key generated by default as identity,
  nome text not null,
  estrelas integer not null default 5,
  comentario text,
  imagens text[] default '{}'::text[],
  instagram text,
  aprovado boolean null default false,
  created_at timestamptz null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  client_name text not null,
  client_phone text not null,
  client_email text,
  service_id integer references public.services(id) on delete set null,
  appointment_date date not null,
  appointment_time text not null,
  status text null default 'confirmado',
  created_at timestamptz null default now()
);

create table if not exists public.blocked_slots (
  id uuid primary key default gen_random_uuid(),
  block_date date not null,
  block_time text,
  reason text,
  created_at timestamptz not null default now()
);

-- ---------- SEGURANCA (modelo Barbearia: RLS restrito) ----------

alter table public.services      enable row level security;
alter table public.feedbacks     enable row level security;
alter table public.appointments  enable row level security;
alter table public.blocked_slots enable row level security;

-- PUBLICO: le catalogo e feedbacks aprovados; cria feedback/agendamento
create policy "publico le services" on public.services
  for select to anon using (true);

create policy "publico le feedbacks aprovados" on public.feedbacks
  for select to anon using (aprovado = true);

create policy "publico envia feedback" on public.feedbacks
  for insert to anon with check (true);

create policy "publico cria agendamento" on public.appointments
  for insert to anon with check (true);

-- plans/clients/blocked_slots/escritas ficam SEM policy:
-- apenas o servidor (service role) acessa, como na Barbearia.
