-- Rastreio de cliques no WhatsApp (executar no SQL Editor do Supabase)
create table if not exists cliques_whatsapp (
  id bigint generated by default as identity primary key,
  origem text not null,
  campanha text,
  criado_em timestamptz default now()
);

alter table cliques_whatsapp enable row level security;
